# Chapter 2 Exercises

*Note: The problem numbering and internal references match the original source images exactly.*

In [1]:
import numpy as np
import math

1. Assign the value 2 to the variable x and the value 3 to the variable y. Clear just the variable x.

In [4]:
x = 2
y = 3
del x

2. Write a line of code that generates the following error:

```text
NameError: name 'x' is not defined
```

In [5]:
print(x)

NameError: name 'x' is not defined

1. Let x = 10 and y = 3. Write a line of code that will make each of the following assignments.

```text
u = x + y
v = xy
w = x/y
z = sin(x)
r = 8sin(x)
s = 5sin(xy)
p = x**y
```

In [7]:
x = 10
y = 3

u, v, w, z, r, s, p = x + y, x * y, x / y, math.sin(x), 8 * math.sin(x), 5 * math.sin(x * y), pow(x, y)

1. Show all the variables in the Jupyter notebook after you finish problem 3.

In [8]:
print(f'{u}, {v}, {w}, {z}, {r}, {s}, {p}')

13, 30, 3.3333333333333335, -0.5440211108893698, -4.352168887114958, -4.940158120464309, 1000


2. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function.

In [11]:
S = '123'
N = float(S)

print(type(S))
print(type(N))

<class 'str'>
<class 'float'>


3. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the == operator to show that they are not equal. Use the == operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the == operator to show that s1 and s2 are equal if *upper* method is used on s2.

In [13]:
s1 = 'HELLO'
s2 = 'hello'

print(s1 == s2)
print(s1.lower() == s2)
print(s1 == s2.upper())

False
True
True


4. Use the *print* function to generate the following strings.
* The world 'Engineering' has 11 letters.
* The word 'Book' has 4 letters.

In [14]:
word1 = 'Engineering'
word2 = 'Book'

print(f"The world '{word1}' has {len(word1)} letters.")
print(f"The word '{word2}' has {len(word2)} letters.")

The world 'Engineering' has 11 letters.
The word 'Book' has 4 letters.


5. Check if 'Python' is in 'Python is great!'.

In [15]:
phrase = 'Python is great!'
'Python' in phrase

True

6. Get the last word 'great' from 'Python is great!'

In [23]:
print(phrase[-6:-1])

great


7. Assign list [1, 8, 9, 15] to a variable *list_a* and insert 2 at index 1 using the *insert* method. Append 4 to the *list_a* using the *append* method.

In [26]:
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
print(list_a)
list_a.append(4)
print(list_a)

[1, 2, 8, 9, 15]
[1, 2, 8, 9, 15, 4]


8. Sort the *list_a* in problem 10 in ascending order.

In [29]:
list_a.sort(reverse=False)
print(list_a)

[1, 2, 4, 8, 9, 15]


9. Turn 'Python is great!' to a list.

In [31]:
phrase_list = phrase.split()
print(phrase_list)

['Python', 'is', 'great!']


10. Create one tuple with element 'One', 1 and assign it to tuple_a

In [32]:
tuple_a = ('One', 1)

11. Get the 2nd element in the tuple_a in problem 13.

In [33]:
tuple_a[1]

1

12. Get the unique element from (2, 3, 2, 3, 1, 2, 5).

In [34]:
tuple_temp = (2, 3, 2, 3, 1, 2, 5)
unique_element = set(tuple_temp)
print(unique_element)

{1, 2, 3, 5}


13. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
* union of set_a and set_b
* intersection of set_a and set_b
* difference of set_a to set_b using *difference* method

In [36]:
set_a = set((2, 3, 2))
set_b = set((1, 2, 3))
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

{1, 2, 3}
{2, 3}
set()


14. Create a dictionary that has the keys 'A', 'B', 'C' with values 'a', 'b', 'c' individually. Print all the keys in the dictionary.

15. Check if key 'B' is in the dictionary defined in problem 17.

16. Create array x and y, where x = [1, 4, 3, 2, 9, 4] and y=[2, 3, 4, 1, 2, 3]. Compute the assignments from Problem 3.

In [38]:
x = np.array([1, 4, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])

17. Generate an array with size 100 evenly spaced between -10 to 10 using *linspace* function in Numpy.

In [40]:
array_ex = np.linspace(-10, 10, 100)
print(array_ex)

[-10.          -9.7979798   -9.5959596   -9.39393939  -9.19191919
  -8.98989899  -8.78787879  -8.58585859  -8.38383838  -8.18181818
  -7.97979798  -7.77777778  -7.57575758  -7.37373737  -7.17171717
  -6.96969697  -6.76767677  -6.56565657  -6.36363636  -6.16161616
  -5.95959596  -5.75757576  -5.55555556  -5.35353535  -5.15151515
  -4.94949495  -4.74747475  -4.54545455  -4.34343434  -4.14141414
  -3.93939394  -3.73737374  -3.53535354  -3.33333333  -3.13131313
  -2.92929293  -2.72727273  -2.52525253  -2.32323232  -2.12121212
  -1.91919192  -1.71717172  -1.51515152  -1.31313131  -1.11111111
  -0.90909091  -0.70707071  -0.50505051  -0.3030303   -0.1010101
   0.1010101    0.3030303    0.50505051   0.70707071   0.90909091
   1.11111111   1.31313131   1.51515152   1.71717172   1.91919192
   2.12121212   2.32323232   2.52525253   2.72727273   2.92929293
   3.13131313   3.33333333   3.53535354   3.73737374   3.93939394
   4.14141414   4.34343434   4.54545455   4.74747475   4.94949495
   5.151515

18. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.

In [41]:
array_a = np.array([-1, 0, 1, 2, 3])
array_a = array_a[array_a > 0]
print(array_a)

[1 2 3]


19. Create an array $y = \begin{pmatrix} 3 & 5 & 3 \\ 2 & 2 & 5 \\ 3 & 8 & 9 \end{pmatrix}$ and calculate the transpose of the array.

In [43]:
y = np.array([[3, 5, 3],
              [2, 2, 5],
              [3, 8, 9]])
transposed_y = y.T

print(y)
print(transposed_y)

[[3 5 3]
 [2 2 5]
 [3 8 9]]
[[3 2 3]
 [5 2 8]
 [3 5 9]]


20. Create a zero array with size (2, 4).

In [46]:
array_zero = np.zeros((2, 4))
print(array_zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


21. Change the 2nd column in the above array to 1.

In [48]:
array_zero[:, 1] = 1
print(array_zero)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


22. Write a cell magic to clear all the variables in the Jupyter notebook