# Chapter 3 Exercises

*Note: Problem definitions have been transcribed from the assignment prompt.*

In [1]:
import numpy as np
import math

1. Recall that the hyperbolic sine, denoted by sinh, is $\frac{\exp(x) - \exp(-x)}{2}$. Write a function `my_sinh(x)`, where the output $y$ is the hyperbolic sine computed on $x$. Assume that $x$ is a 1 by 1 float.

**Test Cases:**
`my_sinh(0)` $\rightarrow$ `0`
`my_sinh(1)` $\rightarrow$ `1.1752`
`my_sinh(2)` $\rightarrow$ `3.6269`

In [2]:
def my_sinh(x):
    y = (math.exp(x) - math.exp(-x)) / 2
    return round(y, 4)
my_sinh(1)

1.1752

2. Write a function `my_checker_board(n)`, where the output $m$ is an $n \times n$ array with the following form: alternating 1s and 0s. Note that the upper-left element should always be 1. Assume that $n$ is a strictly positive integer.

In [3]:
'''
def my_checker_board(n):
    m = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i % 2 != 0:
                if j % 2 != 0:
                    m[i, j] = 1
            else:
                if j % 2 == 0:
                    m[i, j] = 1
    return m
'''

def my_checker_board(n):
    m = np.zeros((n, n))

    m[0::2, 0::2] = 1

    m[1::2, 1::2] = 1
    return m

print(my_checker_board(5))

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


3. Write a function `my_triangle(b, h)` where the output is the area of a triangle with base, $b$, and height, $h$. Recall that the area of a triangle is one-half the base times the height. Assume that $b$ and $h$ are just 1 by 1 float numbers.

In [4]:
def my_triangle(b, h):
    return 1/2 * b * h
my_triangle(1, 2)

1.0

4. Write a function `my_split_matrix(m)`, where $m$ is an array, the output is a list `[m1, m2]` where $m1$ is the left half of $m$, and $m2$ is the right half of $m$. In the case where there is an odd number of columns, the middle column should go to $m1$. Assume that $m$ has at least two columns.

In [5]:
def my_split_matrix(m):
    r, c = m.shape

    m1 = m[:, 0:(c + 1) // 2]
    m2 = m[:, (c + 1) // 2:]

    return [m1, m2]

m = np.array([[1, 2,3], 
              [4, 5, 6]])
print(my_split_matrix(m))

[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


5. Write a function `my_cylinder(r, h)`, where $r$ and $h$ are the radius and height of a cylinder, respectively, and the output is a list `[s, v]` where $s$ and $v$ are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2 h$. Assume that $r$ and $h$ are 1 by 1 float.

In [6]:
def my_cylinder(r, h):
    s = 2 * math.pi * pow(r, 2) + 2 * math.pi * r * h
    v = math.pi * pow(r, 2) * h
    return [s, v]

6. Write a function `my_n_odds(a)`, where $a$ is a one-dimensional array of floats and the output is the number of odd numbers in $a$.

In [8]:
def my_n_odds(a):
    a = a[a % 2 != 0]

    return a.size

my_n_odds(np.array([1, 2, 3, 4, 5]))

3

7. Write a function `my_twos(m, n)`, where the output is an $m \times n$ array of twos. Assume that $m$ and $n$ are strictly positive integers.

In [10]:
def my_twos(m, n):
    return np.ones((m, n)) + np.ones((m, n))

my_twos(3, 5)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

8. Write a lambda function that takes in $x$ and $y$, and output the value of $x - y$.

In [11]:
lambda_function = lambda x, y: x - y
lambda_function(2, 1)

1

9. Write a function `add_string(s1, s2)`, where the output is the concatenation of the strings $s1$ and $s2$.

In [12]:
def add_string(s1, s2):
    return s1 + s2

10. Generate the following errors:
* `TypeError: fun() missing 1 required positional argument: 'a'`
* `IndentationError: expected an indented block`

11. Write a function `greeting(name, age)`, where $name$ is a string, $age$ is a float, and the output is a string 'Hi, my name is XXX and I am XXX years old.' where XXX are the input name and age, respectively.

In [13]:
def greeting(name, age):
    return f'Hi, my name is {name} and I am {age} years old.'
greeting('Carter', 23)

'Hi, my name is Carter and I am 23 years old.'

12. Let $r1$ and $r2$ be the radius of circles with the same center and let $r2>r1$. Write a function `my_donut_area(r1, r2)`, where the output is the area outside of the circle with radius $r1$ and inside the circle with radius $r2$. Make sure that the function is vectorized. Assume that $r1$ and $r2$ are one-dimensional array of the same size.

In [ ]:
def my_donut_area(r1, r2):
    return math.pi * (r2 ** 2 - r1 ** 2)

13. Write a function `my_within_tolerance(A, a, tol)`, where the output is an array or list of the indices in $A$ such that $\vert{}A - a\vert{} < tol$. Assume that $A$ is a one-dimensional float list or array and that $a$ and $tol$ are 1 by 1 floats.

In [16]:
def my_within_tolerance(A, a, tol):
    indices = []
    for i, val in enumerate(A):
        if abs(val - a) < tol:
            indices.append(A[i])
    return indices
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1, 2]

14. Write a function `bounding_array(A, top, bottom)`, where the output is equal to the array $A$ wherever $bottom < A < top$, the output is equal to $bottom$ wherever $A <= bottom$, and the output is equal to $top$ wherever $A >= top$. Assume that A is one-dimensional float array and that $top$ and $bottom$ are 1 by 1 floats.

In [22]:
def bounding_array(A, top, bottom):
    output = []
    for val in A:
        if val <= bottom:
            output.append(bottom)
        elif val >= top:
            output.append(top)
        else:
            output.append(int(val))
    return output

bounding_array(np.arange(-5, 6, 1), 3, -3)

[-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]